version: '2.1'

services:

  fetcher:
    build: web
    container_name: ggstats_fetcher
    hostname: ggstats_fetcher
    restart: always
    command: python3 manage.py fetcher2
    volumes:
      - ./web/src:/src
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "find /src/*.log -mmin -5 | grep '.*'"]
      interval: 1m
    labels:
      autoheal: "true"

  web:
    build: web
    container_name: ggstats_web
    hostname: ggstats_web
    restart: always
    command: ./start.sh
    logging: *default_logging
    volumes:
      - ./web/src:/src
      - ./web/static:/static
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/ | grep title"]
      interval: 1m
    labels:
      autoheal: "true"

  db:
    image: mysql:5.7
    container_name: ggstats_db
    hostname: ggstats_db
    restart: always
    ports:
      - "3306:3306"
    logging: *default_logging
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} ping"]
      interval: 1m
    labels:
      autoheal: "true"

  nginx:
    build: nginx
    container_name: nginx
    hostname: nginx
    restart: always
    logging: *default_logging
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./web/nginx.conf:/etc/nginx/service-ggstats.conf
      - ./gggalka/nginx.conf:/etc/nginx/service-gggalka.conf
      - ./nginx/service.conf:/etc/nginx/service.conf
      - ./nginx/www:/www
      - ./web/static:/static
      - ./gggalka/www:/gggalka
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=UTC
      - LETSENCRYPT=${LETSENCRYPT}
      - LE_EMAIL=${LE_EMAIL}
      - LE_FQDN=${LE_FQDN}

  rss:
    build: rss
    container_name: ggstats_rss
    hostname: ggstats_rss
    command: python3 main.py
    volumes:
      - ./rss/src:/src
      - ./web/static:/static
      - ./rss/data:/data

  # https://github.com/moby/moby/issues/28400
  # https://github.com/willfarrell/docker-autoheal
  autoheal:
    image: willfarrell/autoheal:v0.6.0
    container_name: autoheal
    hostname: autoheal
    restart: always
    logging: *default_logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock