version: '2.1'

services:

  fetcher:
    build: web
    container_name: ggstats_fetcher
    hostname: ggstats_fetcher
    restart: always
    command: python3 manage.py fetcher
    volumes:
      - ./web/src:/src
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    logging: &default_logging
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    healthcheck:
      test: ["CMD-SHELL", "find /src/*.log -mmin -5 | grep '.*'"]
      interval: 1m
    labels:
      autoheal: "true"

  web:
    build: web
    container_name: ggstats_web
    hostname: ggstats_web
    restart: always
    command: ./start.sh
    logging: *default_logging
    volumes:
      - ./web/src:/src
      - ./web/static:/static
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    #ports:
    #  - "8080:8080"
    networks:
      - default
      - nginx
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/ | grep title"]
      interval: 1m
    labels:
      autoheal: "true"

  db:
    image: mysql:5.7
    container_name: ggstats_db
    hostname: ggstats_db
    restart: always
    logging: *default_logging
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} ping"]
      interval: 1m
    labels:
      autoheal: "true"

  # https://github.com/moby/moby/issues/28400
  # https://github.com/willfarrell/docker-autoheal
  autoheal:
    image: willfarrell/autoheal:v0.6.0
    container_name: autoheal
    hostname: autoheal
    restart: always
    logging: *default_logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  nginx:
    external:
      name: nginx_nginx
