services:
  mongo:
    image: mongo
    restart: unless-stopped
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 127.0.0.1:27018:8081

  parser:
    image: python:3.11-alpine
    restart: unless-stopped
    command: sh -c 'cd /app && pip install -r requirements.txt && python main.py'
    volumes:
      - ./parser:/app/
    depends_on:
      - mongo

volumes:
  mongo-data:
