# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-02 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0002_auto_20180930_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ggchat.Channel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ggchat.User')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='userinchat',
            index_together=set([('channel', 'user')]),
        ),
    ]
