# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0003_auto_20181002_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerchannelstats',
            name='hidden',
            field=models.NullBooleanField(),
        ),
    ]
