# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-18 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0004_playerchannelstats_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalstats',
            name='viewers',
        ),
        migrations.AddField(
            model_name='totalstats',
            name='viewers_gg_hidden',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='totalstats',
            name='viewers_gg_hidden_top',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='totalstats',
            name='viewers_gg_top',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='totalstats',
            name='clients',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='totalstats',
            name='users',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='totalstats',
            name='viewers_gg',
            field=models.IntegerField(null=True),
        ),
    ]
