# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
