# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0003_auto_20170629_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumactivation',
            name='resubs',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumstatus',
            name='payment',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
