# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0004_auto_20170629_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumstatus',
            name='payment',
        ),
        migrations.AddField(
            model_name='premiumactivation',
            name='payment',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
