# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0008_auto_20170711_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerChannelStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chat', models.IntegerField()),
                ('viewers', models.IntegerField()),
                ('viewers_gg', models.IntegerField()),
                ('status', models.BooleanField()),
                ('status_gg', models.BooleanField()),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ggchat.Channel')),
            ],
        ),
    ]
