# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0010_playerchannelstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalstats',
            name='viewers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalstats',
            name='viewers_gg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ban',
            name='reason',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commonmessage',
            name='data',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='commonmessage',
            name='type',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='donation',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='donation',
            name='text',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answers',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='warning',
            name='reason',
            field=models.CharField(max_length=800),
        ),
    ]
