# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0011_auto_20170716_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='voice',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
