# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggchat', '0014_auto_20170716_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='voice',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
